default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pong_app_development
  username: <%= ENV.fetch("PG_USERNAME") { "keerthan" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { "" } %>
  host:     <%= ENV.fetch("PG_HOST")     { "localhost" } %>

test:
  <<: *default
  database: pong_app_test
  username: <%= ENV.fetch("PG_USERNAME") { "keerthan" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { "" } %>
  host:     <%= ENV.fetch("PG_HOST")     { "localhost" } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
